name: MythikChatFilter
version: '${project.version}'
main: me.rebelmythik.mythikchatfilter.MythikChatFilter
api-version: 1.19
authors: [ RebelMythik ]
description: Plugin to block / help moderate chat
